# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

#default_platform(:android)

platform :ios do
  desc "Build Debug"
  lane :build_debug do
  match(type: 'development')
  ionic(
    team_id: "34LRA54882",
    platform: 'ios',
    prod: true,
    release: false
    )
  end

  desc "Build Release"
  lane :build_release do
  match(type: 'appstore')
  ionic(
    platform: 'ios',
    prod: true,
    release: true
  )
  end
  
  lane :beta do
    get_certificates           # invokes cert
    get_provisioning_profile   # invokes sigh
    build_app
    end
end

platform :android do
  desc "Build Debug"
  lane :build_debug do   
    ionic(
    platform: 'android',
    prod: true,
    release: false
  )
  end

  desc "Build Release"
  lane :build_release do
  gradle(
    task: 'assemble',
    build_type: 'Release',
    project_dir: 'platforms/android',
    properties: {
      "android.injected.signing.store.file" => 'fastlanedemo.keystore',
      "android.injected.signing.store.password" => 'LynxSpa',
      "android.injected.signing.key.alias" => 'fastlanedemo',
      "android.injected.signing.key.password" => 'LynxSpa',
    }
  )

  gradle(
  task: "bundle",
  build_type: "Release",
  project_dir: 'platforms/android',
  properties: {
      "android.injected.signing.store.file" => 'fastlanedemo.keystore',
      "android.injected.signing.store.password" => 'LynxSpa',
      "android.injected.signing.key.alias" => 'fastlanedemo',
      "android.injected.signing.key.password" => 'LynxSpa',
    }
  )
  end
end